spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: sercurity_ai
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: Secur3P@ssw0rd
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      group-id: security
  data:
    redis:
      host: localhost
  mail:
    host: smtp.163.com
    username: 15524737150@163.com
    password: CDqeie8jnbh8G4Up
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

kangaroohy:
  minio:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: 12345678

logging:
  file:
    name: ./logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: ./logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log
      max-history: 365

ccf:
  security:
    key: hdfsjklfhsdjflkdsajfkjksdlfjlkjdsklfjkldajslkf

malicious:
  detection:
    api:
      url: http://localhost:8000/detect
admin:
  email: 2659279285@qq.com
  password: aA112233
password:
  api:
    url: http://localhost:5500/predict
log:
  api:
    url: http://localhost:6500
    start: /start_monitoring
    end: /stop_monitoring
deepstudylog:
  api:
    url: http://localhost:5000
    process-log: /process_logs
    evaluate: /evaluate



